[32m2023-12-18 16:59:34 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a9bedd7e-f8ca-4e79-a777-5e8db5a268c0 - 12452 - LOGS_CAPTURED - Started capturing logs in process (pid: 12452).
[32m2023-12-18 16:59:34 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a9bedd7e-f8ca-4e79-a777-5e8db5a268c0 - 12452 - SalaryDistribPerDept - STEP_START - Started execution of step "SalaryDistribPerDept".
[32m2023-12-18 16:59:34 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a9bedd7e-f8ca-4e79-a777-5e8db5a268c0 - SalaryDistribPerDept - Loading file from: /Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/tmpjy9nrer1/storage/LoadingCsv using PickledObjectFilesystemIOManager...
[32m2023-12-18 16:59:34 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a9bedd7e-f8ca-4e79-a777-5e8db5a268c0 - 12452 - SalaryDistribPerDept - ASSET_OBSERVATION - DagsterEventType.ASSET_OBSERVATION for step SalaryDistribPerDept
[32m2023-12-18 16:59:34 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a9bedd7e-f8ca-4e79-a777-5e8db5a268c0 - 12452 - SalaryDistribPerDept - LOADED_INPUT - Loaded input "LoadingCsv" using input manager "io_manager"
[32m2023-12-18 16:59:34 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - a9bedd7e-f8ca-4e79-a777-5e8db5a268c0 - 12452 - SalaryDistribPerDept - STEP_INPUT - Got input "LoadingCsv" of type "Any". (Type check passed).
[32m2023-12-18 16:59:34 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - a9bedd7e-f8ca-4e79-a777-5e8db5a268c0 - 12452 - SalaryDistribPerDept - STEP_FAILURE - Execution of step "SalaryDistribPerDept" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "SalaryDistribPerDept"::

KeyError: 'Column not found: annual salary'

Stack Trace:
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/dap_dagster_project/DAP-project/govt_employee_analysis/govt_employee_analysis/assets.py", line 147, in SalaryDistribPerDept
    average_salary_by_department = employee_df.groupby('department')['annual salary'].mean().sort_values()
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/generic.py", line 1416, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirmalgeorge/anaconda3/lib/python3.11/site-packages/pandas/core/base.py", line 248, in __getitem__
    raise KeyError(f"Column not found: {key}")
[0m
